<?php

declare(strict_types=1);

namespace JamesGifford\Hold\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use JamesGifford\Hold\Console\Commands\Concerns\InteractsWithHoldModes;
use JamesGifford\Hold\HoldState;
use JamesGifford\Hold\SignupContext;
use JamesGifford\Hold\Support\TeamNotifier;

/**
 * Activates a hold — the unified front door for both modes:
 *
 *  - prelaunch   package-owned "coming soon" page (flag file + activation token)
 *  - maintenance Laravel's native `php artisan down`, invoked with a bypass
 *                secret (the underlying mechanism is untouched)
 *
 * Only one hold may be active at a time: if any hold is already active, this
 * refuses and names it, telling you to disable it first. There is no override —
 * run `jamesgifford:hold:disable` and try again.
 */
final class EnableCommand extends Command
{
    use InteractsWithHoldModes;

    protected $signature = 'jamesgifford:hold:enable {mode : Which hold to activate: prelaunch or maintenance}';

    protected $description = 'Activate a hold (prelaunch or maintenance). Only one may be active at a time.';

    public function handle(HoldState $state): int
    {
        $mode = strtolower(trim((string) $this->argument('mode')));

        if (! in_array($mode, ['prelaunch', 'maintenance'], true)) {
            $this->error("Unknown mode '{$mode}'. Use 'prelaunch' or 'maintenance'.");

            return self::FAILURE;
        }

        if (($active = $this->activeHoldMode()) !== null) {
            $this->error("A hold is already active: {$active}.");
            $this->line('Only one hold mode may be active at a time. Run this first, then retry:');
            $this->newLine();
            $this->line('    php artisan jamesgifford:hold:disable');

            return self::FAILURE;
        }

        $result = $mode === 'prelaunch'
            ? $this->enablePrelaunch($state)
            : $this->enableMaintenance();

        if ($result === self::SUCCESS) {
            $this->printHoldStatus();
        }

        return $result;
    }

    private function enablePrelaunch(HoldState $state): int
    {
        $state->enable();

        $this->info('Prelaunch ("coming soon") mode enabled. Visitors now see the holding page.');

        // Prelaunch has no framework event, so the team notice is sent here.
        if (TeamNotifier::holdEnabled(SignupContext::Prelaunch)) {
            $this->line('Sent the "hold enabled" notice to your team addresses.');
        }

        $this->printPreviewLink($state);

        return self::SUCCESS;
    }

    private function enableMaintenance(): int
    {
        // Invoke Laravel's native maintenance mode with a generated bypass
        // secret. The down command dispatches MaintenanceModeEnabled, so the
        // team notice fires via the package listener (exactly once) — do not
        // send it here too.
        $secret = Str::random(40);

        $code = $this->call('down', ['--secret' => $secret]);

        if ($code !== self::SUCCESS) {
            $this->error('Failed to enable maintenance mode (see output above).');

            return self::FAILURE;
        }

        $this->info('Maintenance mode enabled (Laravel `down`). Visitors now see the maintenance page.');
        $this->newLine();
        $this->line('Bypass maintenance mode (sets a cookie for you) with this secret link:');
        $this->newLine();
        $this->line('    '.url($secret));

        return self::SUCCESS;
    }

    private function printPreviewLink(HoldState $state): void
    {
        if (! Route::has('hold.preview')) {
            $this->newLine();
            $this->line('Package routes are not registered (routes.register = false), so no preview');
            $this->line('link can be generated. Wire the published routes stub to enable /preview.');

            return;
        }

        // Carry the current activation token so the link is revoked the moment
        // the hold is disabled (and re-enabling issues a fresh one).
        $this->newLine();
        $this->line('Preview the real app (sets a bypass cookie) with this signed link:');
        $this->newLine();
        $this->line('    '.URL::signedRoute('hold.preview', ['token' => $state->token()]));
    }
}
